### ISSUE TITLE
Very slow to open, and no highlighting with neovim

### ISSUE THREAD

**Issue by wamoyo** [digitaltoad/vim-pug#88]
When opening jade files with neovim, the editor lags before opening the file, and then opens it without syntax highlighting. Does the plugin not play nice with neovim?

**Comment by digitaltoad** [comment]
I actually use Neovim as my main and haven't had any issues although most of the time any real slowness that I have found aside from any that I have noted in the issues is usually caused by one of the many js plugins. This has been a known problem and most likely due to my very limited knowledge of VimL.

**Comment by wamoyo** [comment]
Is there a way I can debug it? I've got no error codes. No real idea where to start to try to fix this problem. Upon removing it ana reinstalling it, I get syntax highlighting the first time, and then no highlighting all after that, and a huge lag when opening jade files.

**Comment by digitaltoad** [comment]
The easiest way is to remove all plugins and aside from Jade and then add them one by one. This can be made much easier by using a plugin manager. If you want to take a shot in the dark, remove any extra (added by you) js highlighter plugins first before the clean room attempt.

**Comment by wamoyo** [comment]
Okay, css color plugin was causing slowness, but I still don't have syntax highlighting.

Do I have to name all my files with a .pug extension?

**Comment by wamoyo** [comment]
Hahaa, lucky guess.
